// Generated by scripts/generate-article-slugs.mjs — do not edit by hand.
//
// Slugs of every published article, in either language. analyticsPath() checks
// a path under /artigos against this list instead of trusting the URL.
export const PUBLISHED_ARTICLE_SLUGS: readonly string[] = [

];
