'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Globe2, Map, Users, SlidersHorizontal, Pause, Play, X, Link2 } from 'lucide-react';
import { ATLAS_PEOPLE, ATLAS_RELEASE, REGIONS, EMPTY_COHORT, matches, regionPeople, shares, readAtlasState, atlasQuery, type Cohort } from '@/lib/atlas/population';
import { FIELD_LABELS, LENSES, type Lens } from '@/lib/miniatura/population';
import { AtlasMap, ATLAS_COLOURS } from './AtlasMap';
import './atlas.css';
import { HouseholdInspector } from '@/components/miniatura/HouseholdInspector';
import '../miniatura/miniatura.css';
import { LocalMap } from './LocalMap';
import { MUNICIPALITIES, municipalityFor } from '@/lib/atlas/geography';

export function Atlas({locale}:{locale:'pt'|'en'}){
 const pt=locale==='pt';
 const panelRef=useRef<HTMLElement>(null),workspaceRef=useRef<HTMLDivElement>(null);
 const [panelOpen,setPanelOpen]=useState(false);
 const [selectedHouse,setSelectedHouse]=useState<number|null>(null),[selectedPerson,setSelectedPerson]=useState<number|null>(null);
 const [municipality,setMunicipality]=useState(''),[parish,setParish]=useState('');
 const town=municipalityFor(municipality);
 useEffect(()=>{if(selectedHouse!==null){panelRef.current?.scrollTo({top:0});if((workspaceRef.current?.getBoundingClientRect().top??0)<60)workspaceRef.current?.scrollIntoView({block:'start',behavior:'instant'});}},[selectedHouse,parish]);
 function clearHouse(){setSelectedHouse(null);setSelectedPerson(null);}
 function openHouse(code:string,id:number){setParish(code);setMode('map');setSelectedHouse(id);setSelectedPerson(regionPeople(region).find(p=>p.household===id)?.id??null);setPanelOpen(true);}
 function zoomBack(){if(selectedHouse!==null){clearHouse();setPanelOpen(false);}else if(parish)chooseParish('');else if(municipality)chooseMunicipality('');else chooseRegion('Portugal');}
 const parishName=town?.parishes.find(p=>p.code===parish)?.name;
 function chooseRegion(value:string){clearHouse();setRegion(value);setMunicipality('');setParish('');}
 function chooseMunicipality(value:string){clearHouse();setMunicipality(value);setParish('');setMode('map');}
 function chooseParish(value:string){clearHouse();setParish(value);setMode('map');}
 const [region,setRegion]=useState('Portugal'),[compare,setCompare]=useState('Porto');
 const [mode,setMode]=useState<'map'|'distribution'|'compare'>('map'),[lens,setLens]=useState<Lens>('age');
 const [cohort,setCohort]=useState<Cohort>(EMPTY_COHORT),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const query=new URLSearchParams(window.location.search);if(!query.has('r')||query.get('r')===ATLAS_RELEASE){const state=readAtlasState(query);setRegion(state.region);setMunicipality(state.municipality);setParish(state.parish);setCompare(state.compare);setMode(state.mode);setLens(state.lens);setCohort(state.cohort);const home=query.has('home')?Number(query.get('home')):NaN;const residents=regionPeople(state.region).filter(p=>p.household===home);if(state.parish&&residents.length){setSelectedHouse(home);const person=Number(query.get('person'));setSelectedPerson(residents.find(p=>p.id===person)?.id??residents[0].id);setPanelOpen(true);}}else setNotice(pt?'Esta ligação usa outra versão. A demonstração atual foi reposta.':'This link uses another version. The current demo has been restored.');setReady(true);},[pt]);
 useEffect(()=>{if(!ready)return;const query=atlasQuery({region,compare,mode,lens,cohort,municipality,parish});window.history.replaceState(null,'',`${window.location.pathname}?${query}${selectedHouse!==null&&parish?`&home=${selectedHouse}&person=${selectedPerson??''}`:''}`);},[ready,region,compare,mode,lens,cohort,municipality,parish,selectedHouse,selectedPerson]);
 const population=regionPeople(region),selected=population.filter(p=>matches(p,cohort)),other=regionPeople(compare),otherSelected=other.filter(p=>matches(p,cohort));
 const active=cohort.age>=0||cohort.employment>=0||cohort.alone;
 const percent=(n:number,total:number)=>new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format(total?n/total:0);
 const household=selected[0];
 function meetHousehold(){
  if(!household)return;
  const m=town??MUNICIPALITIES.find(m=>m.region===household.region)!;
  const code=parish||m.parishes[0].code;
  setRegion(m.region);setMunicipality(m.code);setParish(code);setMode('map');setSelectedHouse(household.household);setSelectedPerson(household.id);setPanelOpen(true);
 }
 async function share(){try{await navigator.clipboard.writeText(window.location.href);setNotice(pt?'Ligação copiada com os lugares e filtros escolhidos.':'Link copied with your selected places and filters.');}catch{setNotice(pt?'Podes copiar a ligação da barra de endereços.':'Copy the link from your address bar.');}}
 return <main id="main-content" className="atlas-shell">
  <div className="atlas-kicker"><span><Globe2 size={15}/>{pt?'O ATLAS HUMANO':'THE HUMAN ATLAS'}</span><span>{pt?'PRÉVIA · POPULAÇÃO FICTÍCIA':'PREVIEW · FICTIONAL POPULATION'}</span></div>
  <header className="atlas-heading"><div><h1>{pt?<>Portugal inteiro.<br/><em>Encontra o teu lugar.</em></>:<>All of Portugal.<br/><em>Find your place.</em></>}</h1><p>{pt?'Do país às pessoas. Uma nova forma de explorar quem somos.':'From a country to its people. A new way to explore who we are.'}</p></div><button className="atlas-share" onClick={share}><Link2 size={16}/>{pt?'Partilhar perspetiva':'Share this view'}</button></header>
  <div ref={workspaceRef} className="atlas-workspace atlas-immersive" data-panel-open={panelOpen}>
   <section className="atlas-world" aria-label={pt?'Explorar Portugal':'Explore Portugal'}>
    <div className="atlas-world-top"><div className="atlas-modes" role="group" aria-label={pt?'Perspetiva':'View'}>{(['map','distribution','compare'] as const).map((m,i)=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{i===0?<Map size={15}/>:i===1?<Users size={15}/>:null}{(pt?['Território','Pessoas','Comparar']:['Territory','People','Compare'])[i]}</button>)}</div><button className="atlas-profile-toggle" aria-label={pt?'Lugares e perfil':'Places and profile'} aria-expanded={panelOpen} aria-controls="atlas-profile-panel" onClick={()=>setPanelOpen(!panelOpen)}><SlidersHorizontal size={16}/><span>{pt?'Lugares e perfil':'Places and profile'}</span></button><button className="atlas-pause" onClick={()=>setPaused(!paused)} aria-label={paused?(pt?'Retomar movimento':'Resume motion'):(pt?'Pausar movimento':'Pause motion')}>{paused?<Play size={17}/>:<Pause size={17}/>}</button></div>
    <div className="atlas-breadcrumb" data-root={region==='Portugal'}><button onClick={()=>chooseRegion('Portugal')}>Portugal</button>{region!=='Portugal'&&<><span>/</span><button aria-label={`${pt?'Voltar ao distrito ou região':'Back to district or region'}: ${region}`} onClick={()=>chooseMunicipality('')}>{region}</button>{town&&mode==='map'&&<><span>/</span><button aria-label={`${pt?'Voltar ao município':'Back to municipality'}: ${town.name}`} onClick={()=>chooseParish('')}>{town.name}</button></>}{parishName&&mode==='map'&&<><span>/</span><button onClick={()=>{clearHouse();setPanelOpen(false);}}>{parishName}</button></>}<button aria-label={pt?'Ver todo o país':'See the whole country'} onClick={()=>chooseRegion('Portugal')}><X size={13}/></button></>}</div>
    {mode==='compare'?<div className="atlas-comparison"><div className="atlas-compare-intro"><span>{pt?'DOIS LUGARES. A MESMA ESCALA.':'TWO PLACES. THE SAME SCALE.'}</span><h2>{pt?'O que nos aproxima?':'What connects us?'}</h2><p>{pt?'Proporções nos exemplos fictícios. Cada ponto representa 1% do grupo em destaque.':'Proportions in the fictional examples. Each dot represents 1% of the highlighted group.'}</p></div><div className="atlas-compare-grid">{[{name:region,people:selected,total:population.length},{name:compare,people:otherSelected,total:other.length}].map((item,index)=>{const values=shares(item.people,lens);return <div key={index} className="atlas-compare-place"><label htmlFor={`atlas-place-${index}`}>{index===0?(pt?'Primeiro lugar':'First place'):(pt?'Segundo lugar':'Second place')}</label><select id={`atlas-place-${index}`} value={item.name} onChange={e=>index===0?chooseRegion(e.target.value):setCompare(e.target.value)}><option>Portugal</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select><div className="atlas-hundred" aria-label={pt?'100 pontos normalizados pela distribuição':'100 dots normalized to the distribution'}>{item.people.length?Array.from({length:100},(_,i)=>{let sum=0;const group=values.findIndex(v=>{sum+=v;return (i+.5)/100<=sum;});return <span key={i} style={{background:ATLAS_COLOURS[Math.max(0,group)]}}/>;}):<p>{pt?'Sem correspondências':'No matches'}</p>}</div><p className="atlas-sample">{item.people.length} / {item.total} {pt?'pessoas fictícias':'fictional people'} · {percent(item.people.length,item.total)}</p><div className="atlas-compare-bars">{values.map((v,i)=><div key={i}><span>{FIELD_LABELS[locale][lens][i]}<strong>{percent(v,1)}</strong></span><div><i style={{width:`${v*100}%`,background:ATLAS_COLOURS[i]}}/></div></div>)}</div></div>;})}</div></div>:<div className="atlas-map-stack"><div hidden={mode!=='distribution'}><AtlasMap locale={locale} region={region} cohort={cohort} lens={lens} distribution={true} paused={paused} onRegion={chooseRegion}/></div><div hidden={mode!=='map'} className="atlas-continuous-layer"><LocalMap locale={locale} region={region} municipality={municipality} parish={parish} onRegion={chooseRegion} onMunicipality={chooseMunicipality} onParish={chooseParish} onBack={zoomBack} cohort={cohort} lens={lens} paused={paused} selectedHouse={selectedHouse} selectedPerson={selectedPerson} onHouse={openHouse}/></div></div>}

    <div className="atlas-world-bottom"><div className="atlas-legend" >{FIELD_LABELS[locale][lens].map((label,i)=><span key={label}><i style={{background:ATLAS_COLOURS[i]}}/>{label}</span>)}</div><p>{mode==='map'?(pt?(region==='Portugal'?'Cada ponto é uma pessoa fictícia. Clica num distrito ou região.':'As mesmas pessoas fictícias acompanham o zoom.'):(region==='Portugal'?'Each dot is a fictional person. Select a district or region.':'The same fictional people follow the zoom.')):mode==='distribution'?(pt?'As mesmas pessoas, agrupadas. Os filtros mantêm a seleção.':'The same people, grouped. Filters preserve the selection.'):(pt?'Comparação distrital · percentagens arredondadas.':'District comparison · rounded percentages.')}</p></div>
   </section>
   <aside ref={panelRef} id="atlas-profile-panel" className="atlas-panel" inert={!panelOpen} aria-hidden={!panelOpen}><div className="atlas-drawer-title"><strong>{pt?'A tua perspetiva':'Your perspective'}</strong><button aria-label={pt?'Fechar painel':'Close panel'} onClick={()=>setPanelOpen(false)}><X size={18}/></button></div>
    {selectedHouse!==null&&parish&&<div className="atlas-inline-house"><HouseholdInspector household={selectedHouse} locale={locale} selectedPerson={selectedPerson} onPersonSelect={setSelectedPerson} onClose={()=>setSelectedHouse(null)} onChange={id=>{const homes=[...new Set(regionPeople(region).map(p=>p.household))];const direction=id===(selectedHouse+1)%30?1:-1;const next=homes[(homes.indexOf(selectedHouse)+direction+homes.length)%homes.length];setSelectedHouse(next);setSelectedPerson(regionPeople(region).find(p=>p.household===next)?.id??null);}}/></div>}

    <label className="atlas-field" htmlFor="atlas-region">{pt?'01 / ESCOLHE UM LUGAR':'01 / CHOOSE A PLACE'}<select id="atlas-region" value={region} onChange={e=>chooseRegion(e.target.value)}><option>Portugal</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label>
    {region!=='Portugal'&&<div className="atlas-local-selectors"><label htmlFor="atlas-municipality">{pt?'Município':'Municipality'}<select id="atlas-municipality" value={municipality} onChange={e=>chooseMunicipality(e.target.value)}><option value="">{pt?'Todos os municípios':'All municipalities'}</option>{MUNICIPALITIES.filter(m=>m.region===region).sort((a,b)=>a.name.localeCompare(b.name,'pt')).map(m=><option key={m.code} value={m.code}>{m.name}</option>)}</select></label>{town&&<label htmlFor="atlas-parish">{pt?'Freguesia':'Parish'}<select id="atlas-parish" value={parish} onChange={e=>chooseParish(e.target.value)}><option value="">{pt?'Todas as freguesias':'All parishes'}</option>{[...town.parishes].sort((a,b)=>a.name.localeCompare(b.name,'pt')).map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select></label>}<p>{parishName?`${parishName} · ${parish}`:town?`${town.parishes.length} ${pt?'freguesias':'parishes'}`:`${MUNICIPALITIES.filter(m=>m.region===region).length} ${pt?'municípios':'municipalities'}`} · CAOP 2021</p><p>{pt?'Estas pessoas e casas são ilustrativas e acompanham o zoom. Não são estimativas da população local.':'These illustrative people and homes follow the zoom. They are not local population estimates.'}</p></div>}
    <label className="atlas-field" htmlFor="atlas-lens">{pt?'02 / MUDA O OLHAR':'02 / CHANGE YOUR LENS'}<select id="atlas-lens" value={lens} onChange={e=>setLens(e.target.value as Lens)}>{LENSES.map((l,i)=><option value={l} key={l}>{(pt?['Idade','Escolaridade','Emprego','Transportes']:['Age','Education','Employment','Transport'])[i]}</option>)}</select></label>
    <div className="atlas-cohort"><div className="atlas-cohort-title"><Users size={18}/><h2>{pt?'Pessoas como…':'People like…'}</h2>{active&&<button onClick={()=>setCohort(EMPTY_COHORT)}>{pt?'Limpar':'Clear'}</button>}</div><p>{pt?'Escolhe um perfil e encontra-o no mapa.':'Choose a profile and find it on the map.'}</p><label htmlFor="atlas-age">{pt?'Idade':'Age'}<select id="atlas-age" value={cohort.age} onChange={e=>setCohort({...cohort,age:Number(e.target.value)})}><option value={-1}>{pt?'Todas as idades':'All ages'}</option>{FIELD_LABELS[locale].age.map((l,i)=><option value={i} key={l}>{l}</option>)}</select></label><label htmlFor="atlas-employment">{pt?'Atividade':'Activity'}<select id="atlas-employment" value={cohort.employment} onChange={e=>setCohort({...cohort,employment:Number(e.target.value)})}><option value={-1}>{pt?'Todas as situações':'All situations'}</option>{FIELD_LABELS[locale].employment.map((l,i)=><option value={i} key={l}>{l}</option>)}</select></label><label className="atlas-check"><input type="checkbox" checked={cohort.alone} onChange={e=>setCohort({...cohort,alone:e.target.checked})}/>{pt?'Vive sozinho':'Lives alone'}</label></div>
    <div className="atlas-result" aria-live="polite"><span>{region} · {pt?'EXEMPLO FICTÍCIO':'FICTIONAL EXAMPLE'}</span><strong>{selected.length}<small> / {population.length}</small></strong><p>{pt?'pessoas correspondem à tua seleção':'people match your selection'} · {percent(selected.length,population.length)}</p>{selected.length===0&&<p>{pt?'Este exemplo não contém esse perfil. Experimenta retirar um filtro.':'This example has no matching profile. Try removing a filter.'}</p>}{selected.length===0&&<button className="atlas-reset" onClick={()=>setCohort(EMPTY_COHORT)}>{pt?'Limpar os filtros':'Clear the filters'}</button>}</div>
    {household&&<button className="atlas-enter" onClick={meetHousehold}><div><span>{pt?'POR DENTRO DA ESTATÍSTICA':'INSIDE THE STATISTIC'}</span><strong>{pt?'Conhece um agregado':'Meet a household'}</strong><small>{household.region} · {household.size} {pt?(household.size===1?'pessoa fictícia':'pessoas fictícias'):(household.size===1?'fictional person':'fictional people')}</small></div><ArrowUpRight size={23}/></button>}
   </aside>
  </div>
  <div className="atlas-prompts"><span>{pt?'EXPERIMENTA':'TRY IT'}</span><button onClick={()=>{setCohort({age:3,employment:-1,alone:true});setLens('age');setMode('distribution');chooseRegion('Portugal');if(!window.matchMedia('(max-width:720px)').matches)setPanelOpen(true);}}>{pt?'Quem envelhece sozinho?':'Who grows older alone?'}<ArrowRight size={15}/></button><button onClick={()=>{setCohort(EMPTY_COHORT);chooseRegion('Lisboa');setCompare('Bragança');setMode('compare');setLens('age');}}>{pt?'Lisboa e Bragança, lado a lado':'Lisboa and Bragança, side by side'}<ArrowRight size={15}/></button><button onClick={()=>{setMode(mode==='distribution'?'map':'distribution');}}>{pt?'Vê o país transformar-se em pessoas':'Watch the country become people'}<ArrowRight size={15}/></button></div>
  <footer className="atlas-method" id="metodo"><p><strong>{pt?'Geografia real. População de demonstração.':'Real geography. Demonstration population.'}</strong> {pt?`As ${ATLAS_PEOPLE.length} pessoas deste atlas foram inventadas para testar a experiência. As diferenças entre lugares não representam Portugal.`:`The ${ATLAS_PEOPLE.length} people in this atlas were invented to test the experience. Differences between places do not represent Portugal.`}</p><details><summary>{pt?'O que chega com a população nacional?':'What comes with the national population?'}</summary><p>{pt?'A ligação à população sintética nacional depende da versão aprovada para publicação. Os totais, filtros e comparações serão calculados a partir dessa versão. O detalhe por município e freguesia depende da cobertura e qualidade disponibilizadas. As ilustrações não localizam pessoas em moradas reais.':'The national synthetic population will be connected when a release is approved for publication. Totals, filters and comparisons will be calculated from that release. Municipality and parish detail depends on available coverage and quality. Illustrations do not place people at real addresses.'}</p><p>{ATLAS_RELEASE}</p></details></footer><p className="atlas-notice" role="status">{notice}</p>
 </main>;
}
