import { setRequestLocale } from '@/i18n/request-locale';
import { Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { SiteFooter } from '@/components/SiteFooter';
import { PageHero } from '@/components/PageHero';
import { Mosaic } from '@/components/brand/Mosaic';
import { SectionNotes } from '@/components/articles/SectionNotes';
import { ParishSearch } from '@/components/population/ParishSearch';
import { PopulationSectionNav } from '@/components/population/SectionNav';
import { PopulationMap } from '@/components/population/map/PopulationMap';
import { KeyFacts } from '@/components/population/hub/KeyFacts';
import { NationalAgeCard } from '@/components/population/hub/NationalAgeCard';
import { EntryCards } from '@/components/population/hub/EntryCards';
import { RegionsIndex } from '@/components/population/hub/RegionsIndex';
import { regionEntries } from '@/components/population/hub/places';
import { POPULATION_RELEASE } from '@/lib/config/population';
import { createPageMetadata } from '@/lib/metadata';
import { readCells } from '@/lib/population/compact';
import { HONESTY, type Locale } from '@/lib/population/labels';
import { loadPopulationMeta, loadPopulationNational, loadPopulationPlaces } from '@/lib/utils/population-data-loader';
import type { Metadata } from 'next';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  setRequestLocale(locale);
  const pt = locale !== 'en';
  return createPageMetadata({
    locale,
    path: '/populacao',
    title: pt
      ? 'Quem vive em Portugal, freguesia a freguesia?'
      : 'Who lives in Portugal, parish by parish?',
    description: pt
      ? 'Uma população sintética aberta para as 3 092 freguesias dos Censos 2021: procura a tua freguesia, explora o mapa e descarrega os dados.'
      : 'An open synthetic population for the 3,092 parishes of the 2021 Census: find your parish, explore the map and download the data.',
    index: true,
  });
}

export default async function PopulationHub({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params;
  const locale: Locale = raw === 'en' ? 'en' : 'pt';
  setRequestLocale(locale);
  const pt = locale === 'pt';
  const [meta, places, national] = await Promise.all([loadPopulationMeta(), loadPopulationPlaces(), loadPopulationNational()]);
  const regions = places ? regionEntries(places, locale) : [];
  const ageCells = meta && national && national.response.decision !== 'refuse'
    ? readCells(national.response, meta.recipes.national_age, locale)
    : null;

  return (
    <div className="min-h-screen bg-paper">
      <Header />
      <main id="main-content" tabIndex={-1}>
      <PageHero
        field="periwinkle"
        // The search's suggestion list opens below the hero; the art stays inside its own box.
        className="overflow-visible!"
        icon={<Users aria-hidden="true" className="h-4 w-4" />}
        eyebrow={pt ? `População sintética · v${POPULATION_RELEASE} · Censos 2021` : `Synthetic population · v${POPULATION_RELEASE} · 2021 Census`}
        title={pt ? 'Quem vive em Portugal, freguesia a freguesia?' : 'Who lives in Portugal, parish by parish?'}
        lede={
          <>
            {pt
              ? 'Pessoas e agregados gerados por um modelo, freguesia a freguesia, a partir das tabelas dos Censos 2021 de cada lugar: idades, trabalho, escolaridade e famílias. Escolhe uma freguesia para ver o que a população gerada diz sobre ela.'
              : 'People and households generated by a model, parish by parish, from each place’s 2021 Census tables: ages, work, education and families. Pick a parish to see what the generated population says about it.'}
            <span className="mt-2 block text-[15px] text-stone-600">{HONESTY.positioning[locale]}</span>
          </>
        }
        art={<Mosaic variant="cover" className="h-full w-full" ground="transparent" colors={['mintSoft', 'mustardSoft', 'coralSoft']} />}
        actions={
          <ParishSearch
            locale={locale}
            withLocation
            label={pt ? 'Procura a tua freguesia' : 'Find your parish'}
            className="w-full max-w-xl"
          />
        }
      />
      <PopulationSectionNav current="hub" locale={locale} />

      <div className="mx-auto max-w-7xl px-4 py-8 md:py-10">
        {meta ? (
          <KeyFacts
            locale={locale}
            persons={meta.counts.persons}
            households={meta.counts.households}
            parishes={meta.counts.parishes}
            municipalities={meta.counts.municipalities}
            tiers={meta.counts.tiers}
          />
        ) : (
          <p className="rounded-2xl border border-line bg-cream p-5 text-sm text-stone-600">
            {pt
              ? 'Os dados da população sintética não estão disponíveis neste momento. Tenta novamente mais tarde.'
              : 'The synthetic population data is not available right now. Please try again later.'}
          </p>
        )}

        <section aria-labelledby="mapa" className="mt-12">
          <h2 id="mapa" className="text-2xl md:text-3xl">{pt ? 'Explora o mapa' : 'Explore the map'}</h2>
          <p className="mb-4 mt-2 max-w-3xl text-[15px] leading-relaxed text-stone-600">
            {pt
              ? 'Aproxima um distrito, depois um concelho, e escolhe uma freguesia. A cor de cada freguesia é só o seu nível de qualidade (A, B ou C), que junta o ajuste às tabelas do INE e o número de residentes; não é um número da população gerada.'
              : 'Zoom into a district, then a municipality, and pick a parish. A parish’s colour is only its quality tier (A, B or C), which combines the fit to INE’s tables and the number of residents; it is not a figure from the generated population.'}
          </p>
          <PopulationMap locale={locale} />
        </section>

        {ageCells && (
          <section id="idade" aria-labelledby="idade-titulo" className="mt-12 scroll-mt-24">
            <h2 id="idade-titulo" className="mb-4 text-2xl md:text-3xl">{pt ? 'Que idade tem Portugal?' : 'How old is Portugal?'}</h2>
            <NationalAgeCard cells={ageCells} locale={locale} />
          </section>
        )}

        <section aria-labelledby="mais" className="mt-12">
          <h2 id="mais" className="mb-4 text-2xl md:text-3xl">{pt ? 'E agora?' : 'What next?'}</h2>
          <EntryCards locale={locale} />
        </section>

        {regions.length > 0 && (
          <section aria-labelledby="regioes" className="mt-12">
            <h2 id="regioes" className="text-2xl md:text-3xl">{pt ? 'Freguesias por distrito e região autónoma' : 'Parishes by district and autonomous region'}</h2>
            <p className="mb-4 mt-2 max-w-3xl text-[15px] leading-relaxed text-stone-600">
              {pt
                ? 'Cada página lista os concelhos e as freguesias, por ordem alfabética, com a ligação para cada uma.'
                : 'Each page lists the municipalities and parishes in alphabetical order, with a link to each one.'}
            </p>
            <RegionsIndex regions={regions} locale={locale} />
          </section>
        )}
      </div>

      <SectionNotes
        section="demographics"
        locale={locale}
        className="border-t border-line py-10"
        containerClassName="mx-auto max-w-7xl px-4"
      />
      </main>
      <SiteFooter locale={locale} />
    </div>
  );
}
