/**
 * Words for Freguesia misteriosa, in European Portuguese ("tu") and English.
 * Sentence case, questions as headings, no emoji, no exclamation marks.
 */
import type { Locale } from '@/lib/population/labels';

const pt = {
  heroEyebrow: 'População · jogo diário',
  heroTitle: 'Que freguesia é esta?',
  heroLede: 'Uma freguesia por dia, descrita só pelos números da população sintética. Tens seis tentativas, e cada erro abre uma nova pista.',
  heroMeta: 'Uma freguesia nova à meia-noite, hora de Lisboa',
  metaTitle: 'Freguesia misteriosa: que freguesia é esta?',
  metaDescription: 'O jogo diário da população sintética: descobre a freguesia a partir das idades, dos agregados, da escolaridade e do trabalho. Seis tentativas.',

  howTitle: 'Como se joga?',
  howSteps: [
    'Começas com uma pista: as idades das pessoas geradas para a freguesia misteriosa.',
    'Escreve o nome de uma freguesia (ou do concelho) e escolhe-a na lista. Dizemos a que distância ficaste, em que direção está a freguesia certa e se acertaste no concelho ou na região (o distrito, ou a região autónoma).',
    'Cada tentativa falhada abre a pista seguinte: pessoas por agregado, núcleos familiares, escolaridade, condição perante o trabalho e, por fim, quem tem 65 ou mais anos e vive só, a par das casas que juntam crianças e pessoas de 65+.',
    'Tens seis tentativas. À meia-noite de Lisboa chega uma freguesia nova.',
  ],
  howPool: 'Qualquer uma das 3 092 freguesias pode ser a misteriosa, seja qual for o seu nível de qualidade (A, B ou C); no fim, mostramos o nível e o que quer dizer. Podes tentar qualquer uma.',
  howProximity: 'A proximidade compara a tua distância com a maior distância entre duas freguesias de Portugal: 100% é acertar, 0% é estar no extremo oposto do país.',
  howStorage: 'Os teus resultados ficam guardados só neste dispositivo.',

  loading: 'A preparar a freguesia de hoje…',
  loadError: 'Não foi possível carregar o jogo. Verifica a ligação e tenta outra vez.',
  retry: 'Tentar outra vez',

  dayLabel: (n: number) => `N.º ${n}`,
  attempt: (n: number, max: number) => `Tentativa ${n} de ${max}`,
  attemptsUsed: (n: number, max: number) => `${n} de ${max} tentativas usadas`,
  practiceBanner: 'Dia anterior, em modo treino: não conta para as estatísticas.',
  backToToday: 'Voltar à freguesia de hoje',

  cluesTitle: 'Pistas',
  clue: (n: number) => `Pista ${n}`,
  clueLocked: (misses: number) => (misses === 1 ? 'Abre depois de 1 erro' : `Abre depois de ${misses} erros`),
  newClue: 'Nova pista',
  mysteryFigures: 'Valores da freguesia misteriosa.',
  answerFigures: (name: string) => `Valores de ${name}.`,
  fallbackHidden: 'Valores do concelho a que a freguesia pertence: este resultado não foi publicado para a própria freguesia.',
  fallbackNamed: (name: string) => `Valores do concelho de ${name}: este resultado não foi publicado para a própria freguesia.`,
  refused: 'Sem resposta publicada para esta freguesia na versão 1.0. Não mostramos um número que não passou o controlo de qualidade.',
  sourceStamp: 'Censos 2021',

  guessLabel: 'Que freguesia é?',
  guessPlaceholder: 'Nome da freguesia ou do concelho',
  guessesTitle: 'As tuas tentativas',
  emptySlot: (n: number) => `Tentativa ${n}`,
  correct: 'Acertaste',
  distance: 'Distância',
  direction: (words: string) => `A freguesia misteriosa fica ${words}`,
  proximity: 'Proximidade',
  sameMunicipality: 'Mesmo concelho',
  sameRegion: 'Mesma região',

  locatorTitle: 'Onde tentaste',
  locatorAnswer: 'Freguesia misteriosa',
  locatorGuesses: 'Tentativas, numeradas',
  locatorEmpty: 'As tuas tentativas aparecem aqui.',

  wonKicker: (n: number) => (n === 1 ? 'Acertaste à primeira' : `Acertaste em ${n} tentativas`),
  lostKicker: 'Desta vez não foi',
  revealHeading: 'Que freguesia era?',
  residents: 'Residentes (INE, Censos 2021)',
  seePortrait: 'Ver o retrato da freguesia',
  share: 'Partilhar resultado',
  copied: 'Resultado copiado',
  shareFailed: 'Não foi possível partilhar. Copia o texto abaixo.',
  next: 'Próxima freguesia daqui a',
  statsTitle: 'As tuas estatísticas',
  statsNote: 'Contam só os jogos feitos no próprio dia.',
  played: 'Jogos',
  won: 'Vitórias',
  currentStreak: 'Sequência atual',
  bestStreak: 'Melhor sequência',
  distributionTitle: 'Tentativas até acertar',
  distributionLost: 'Falhadas',
  attribution: 'Localização das freguesias: Direção-Geral do Território (DGT), CAOP 2021, licença',

  archiveTitle: 'Dias anteriores',
  archiveLede: 'Joga uma freguesia de um dia que já passou. É treino: não conta para as estatísticas.',
  archiveEmpty: 'Ainda não há dias anteriores: a primeira freguesia misteriosa é a de hoje. Amanhã, esta passa para aqui.',
  archiveSelect: 'Escolher um dia',
  archivePlay: 'Jogar este dia',
  archiveWon: (n: number) => `acertada em ${n}`,
  archiveLost: 'falhada',
  archivePlaying: 'em curso',
  archiveNew: 'por jogar',
};

type Copy = typeof pt;

const en: Copy = {
  heroEyebrow: 'Population · daily game',
  heroTitle: 'Which parish is this?',
  heroLede: 'One parish a day, described only by the synthetic population’s figures. You have six guesses, and each miss opens a new clue.',
  heroMeta: 'A new parish at midnight, Lisbon time',
  metaTitle: 'Mystery parish: which parish is this?',
  metaDescription: 'The synthetic population’s daily game: find the parish from its ages, households, education and work. Six guesses.',

  howTitle: 'How do you play?',
  howSteps: [
    'You start with one clue: the ages of the people generated for the mystery parish.',
    'Type the name of a parish (or its municipality) and pick it from the list. We tell you how far off you are, which way the right parish lies, and whether you got the municipality or the region (the district, or the autonomous region).',
    'Each miss opens the next clue: people per household, family nuclei, education, employment status and, last, who is 65 or over and lives alone, alongside the homes that bring together children and people aged 65+.',
    'You have six guesses. A new parish arrives at midnight, Lisbon time.',
  ],
  howPool: 'Any of the 3,092 parishes can be the mystery one, whatever its quality tier (A, B or C); at the end we show the tier and what it means. You can guess any of them.',
  howProximity: 'Proximity compares your distance with the widest distance between two parishes in Portugal: 100% is a hit, 0% is the far side of the country.',
  howStorage: 'Your results are kept on this device only.',

  loading: 'Getting today’s parish ready…',
  loadError: 'The game could not be loaded. Check your connection and try again.',
  retry: 'Try again',

  dayLabel: (n: number) => `No. ${n}`,
  attempt: (n: number, max: number) => `Guess ${n} of ${max}`,
  attemptsUsed: (n: number, max: number) => `${n} of ${max} guesses used`,
  practiceBanner: 'An earlier day, in practice mode: it does not count towards your stats.',
  backToToday: 'Back to today’s parish',

  cluesTitle: 'Clues',
  clue: (n: number) => `Clue ${n}`,
  clueLocked: (misses: number) => (misses === 1 ? 'Opens after 1 miss' : `Opens after ${misses} misses`),
  newClue: 'New clue',
  mysteryFigures: 'Figures for the mystery parish.',
  answerFigures: (name: string) => `Figures for ${name}.`,
  fallbackHidden: 'Figures for the municipality the parish belongs to: this result was not published for the parish itself.',
  fallbackNamed: (name: string) => `Figures for ${name} municipality: this result was not published for the parish itself.`,
  refused: 'No published answer for this parish in release 1.0. We do not show a number that did not pass the quality check.',
  sourceStamp: '2021 Census',

  guessLabel: 'Which parish is it?',
  guessPlaceholder: 'Parish or municipality name',
  guessesTitle: 'Your guesses',
  emptySlot: (n: number) => `Guess ${n}`,
  correct: 'Got it',
  distance: 'Distance',
  direction: (words: string) => `The mystery parish lies to the ${words}`,
  proximity: 'Proximity',
  sameMunicipality: 'Same municipality',
  sameRegion: 'Same region',

  locatorTitle: 'Where you guessed',
  locatorAnswer: 'Mystery parish',
  locatorGuesses: 'Guesses, numbered',
  locatorEmpty: 'Your guesses appear here.',

  wonKicker: (n: number) => (n === 1 ? 'Got it first time' : `Got it in ${n} guesses`),
  lostKicker: 'Not this time',
  revealHeading: 'Which parish was it?',
  residents: 'Residents (INE, 2021 Census)',
  seePortrait: 'See the parish portrait',
  share: 'Share result',
  copied: 'Result copied',
  shareFailed: 'Sharing did not work. Copy the text below.',
  next: 'Next parish in',
  statsTitle: 'Your stats',
  statsNote: 'Only games played on their own day count.',
  played: 'Played',
  won: 'Won',
  currentStreak: 'Current streak',
  bestStreak: 'Best streak',
  distributionTitle: 'Guesses to get it',
  distributionLost: 'Missed',
  attribution: 'Parish locations: Direção-Geral do Território (DGT), CAOP 2021, licence',

  archiveTitle: 'Earlier days',
  archiveLede: 'Play a parish from a day that has gone. It is practice: it does not count towards your stats.',
  archiveEmpty: 'No earlier days yet: today’s is the first mystery parish. Tomorrow, it moves here.',
  archiveSelect: 'Choose a day',
  archivePlay: 'Play this day',
  archiveWon: (n: number) => `got in ${n}`,
  archiveLost: 'missed',
  archivePlaying: 'in progress',
  archiveNew: 'not played',
};

export const GAME_COPY: Record<Locale, Copy> = { pt, en };
export type GameCopy = Copy;
